Merged dev into main after first sprint
WUoT-software-engineering-group/PetshareApp pull request #22
Opened 2023-03-27 18:54 UTC by Sivvak

2023-03-28 11:24 UTC, kubaurban commented on Src/.config/dotnet-tools.json
Jakiś śmieć?

2023-03-28 11:36 UTC, kubaurban commented on Src/Petshare.WebAPI/.config/dotnet-tools.json
Śmieć?

2023-03-28 11:40 UTC, kubaurban requested changes
@Sivvak albo @sebastianSzarafin te śmiecie co oznaczyłem w komentarzach to rzeczywiście śmiecie?

@sebastianSzarafin bardzo by się przydało jeszcze zrobić default wartości dla kilku kolumn np. data dodania czy update'u i jeszcze autogenerowanie dla wszystkich ID, żeby w kodzie serwisów tego nie robić

2023-03-28 16:47 UTC, Sivvak commented on Src/Petshare.WebAPI/.config/dotnet-tools.json
@sebastianSzarafin to chyba z Twojego commita

2023-03-28 16:52 UTC, Sivvak commented on Src/.config/dotnet-tools.json
Chyba tool do migracji to automatycznie dodaje, bo to z kolei wleciało, jak ja go używałem

2023-03-29 15:39 UTC, Sivvak commented on Src/Petshare.Presentation/Controllers/PetController.cs
> +                ? BadRequest()
Chyba się komentarz nie zapisał idk
W każdym razie imo tutaj bardziej NotFound() pasuje @kubaurban

2023-03-30 19:46 UTC, kubaurban approved these changes

2023-03-30 20:11 UTC, merged